version: '3.8'

services:
  nodejs:
    build:
      context: ./
      dockerfile: dockerfiles/frontend/Dockerfile
    ports:
      - '4200:4200'
    volumes:
      - ./AppConectese:/app
      - /app/node_modules
  server:
    container_name: server
    build:
      context: .
      dockerfile: dockerfiles/nginx/Dockerfile
    ports:
      - '80:80'
    volumes:
      - ./api:/var/www/html
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - php
      - mysql
  php:
    container_name: php
    build:
      context: .
      dockerfile: dockerfiles/php/Dockerfile
    volumes:
      - ./api:/var/www/html
  mysql:
    image: mysql:5.7
    env_file:
      - ./env/mysql.env
  composer:
    build:
      context: .
      dockerfile: dockerfiles/composer/Dockerfile
    volumes:
      - ./api:/var/www/html
    depends_on:
      - php
